### ISSUE TITLE
Inaccurate error information with brackets

### ISSUE THREAD

**Issue by Teddy-van-Jerry** [Teddy-van-Jerry/String_Evaluate#1]
When more left brackets are provided, it can not detect that the error lies with mismatched brackets.
When more right brackets are provided, it simply just ignores them!

**Comment by PracticalMetal** [comment]
Hey, I would like to work on this. Can you suggest me ways to get started?

**Comment by Teddy-van-Jerry** [comment]
@PracticalMetal The problem may be here: the function [`add_new_oper`](https://github.com/Teddy-van-Jerry/String_Evaluate/blob/6c482fcf69c26bf774088ff38324131be9dd83f7/String_Complex.h#L257). I failed to find an effective way to check the validity of brackets.

**Comment by PracticalMetal** [comment]
Understood, I am working on it.

**Comment by PracticalMetal** [comment]
Can you let me know how i can reproduce this issue or some example where you are getting an unexpected output?

**Comment by Teddy-van-Jerry** [comment]
## Example 1
```cpp
cout << eval("(2+3") << endl;
```
Output:
```
ERROR: More operators or functions, or less numbers than expected
At "D:\C++\String_Complex\String_Complex.h " Line 493
(0,0)
```
It found there is a problem, but the error information is not accurate enough.
## Example 2
```cpp
cout << eval("2+3)))") << endl;
```
Output:
```
(5,0)
```
No syntax error is reported.
